name: 测试 Manage Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ManageTag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manage Tag
        uses: infinity-public/action-manage-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-commit: ${{ github.sha }}
          tag-min-count: 10
          tag-min-days: 30
