name: 测试 Manage Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit-sha:
        description: '指定要打标签的 commit SHA（留空则使用最新提交）'
        required: false
        type: string

jobs:
  ManageTag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manage Tag
        uses: infinity-public/action-manage-tag@v1
        with:
          tag-commit: ${{ inputs.commit-sha || github.sha }}
          tag-min-count: 10
          tag-min-days: 30